### ISSUE TITLE
[Feature] ADD SNI server name and custom dial ip support

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/fastdialer#28]

**Comment by EndPositive** [comment]
Hi @ehsandeep @Mzack9999, would it be possible to create a release for this feature?

@securabv is using Nuclei in a highly automatic environment and we would love to support scanning servers that use SN.

**Comment by ehsandeep** [comment]
Done - https://github.com/projectdiscovery/fastdialer/releases/tag/v0.0.14

**Comment by EndPositive** [comment]
Awesome! I guess we just missed the Nuclei release but it would be nice to have this library updated in Nuclei as well.
